[build]
command = "sed -i \"s|API_PLACEHOLDER|${VITE_API_TARGET}|g\" netlify.toml && npm run build"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
from = "/api/*"
to = "API_PLACEHOLDER/:splat"

status = 200
force = true                     # COMMENT: ensure that we always redirect
headers = { X-From = "Netlify" }

# Rewrite a path for signle page appliacation
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
