## This rule redirects to an external API, signing requests with a secret
[[redirects]]
from = "/api/*"
to = "http://43.132.156.239:5090/:splat"

status = 200
force = true # COMMENT: ensure that we always redirect
headers = {X-From = "Netlify"}

# Rewrite a path for signle page appliacation
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
