on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: youbetdao
          number: 2
          token: ${{ secrets.PROJECT_PAT }}
          iteration-field: Iteration
          iteration: last
          new-iteration: current
          statuses: 'Todo,In Progress,In Review'
