name: Sync Main to Dev

on:
  push:
    branches:
      - main

  pull_request: 
    types:
      - closed

  # manual trigger
  workflow_dispatch:

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Gives write access to repository contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Simulate failure (manual trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Simulating failure..."
          exit 1

      - name: Update dev branch
        id: sync
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull origin main
          git fetch origin dev
          git checkout dev
          git merge main
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Feishu notification on success
        if: success()
        # 发送成功通知
        run: |
          timestamp=$(date +%s)
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "interactive",
            "card": {
              "config": { "wide_screen_mode": true },
              "header": {
                "title": { "tag": "plain_text", "content": "✅ Dev Branch Sync Completed" },
                "template": "green"
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Repository:** [${{ github.repository }}](github.com/${{ github.repository }})"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Workflow:** [${{ github.workflow }}](github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Triggered by:** ${{ github.actor }}"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Event:** ${{ github.event_name }}"
                  }
                },
                {
                    "tag": "action",
                    "actions": [
                        {
                            "tag": "button",
                            "text": {
                                "tag": "plain_text",
                                "content": "View Action Details"
                            },
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "type": "primary"
                        }
                    ]
                }
              ]
            }
          }' \
          ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}

      - name: Send Feishu notification on failure
        if: ${ failure() } || ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          timestamp=$(date +%s)
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "interactive",
            "card": {
              "config": { "wide_screen_mode": true },
              "header": {
                "title": { "tag": "plain_text", "content": "🚨 Dev Branch Sync Failed" },
                "template": "red"
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Repository:** [${{ github.repository }}](github.com/${{ github.repository }})"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Workflow:** [${{ github.workflow }}](github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Triggered by:** ${{ github.actor }}"
                  }
                },
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "**Event:** ${{ github.event_name }}"
                  }
                },
                {
                    "tag": "action",
                    "actions": [
                        {
                            "tag": "button",
                            "text": {
                                "tag": "plain_text",
                                "content": "View Action Details"
                            },
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "type": "primary"
                        }
                    ]
                }
              ]
            }
          }' \
          ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}